version: "3.9"

services:

  whisperbox:

    image: whisperbox:latest

    container_name: whisperbox

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod

    restart: unless-stopped